/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author USER
 */
public class Printfile2 extends javax.swing.JFrame {

    /**
     * Creates new form Printfile
     */
    public Printfile2() throws PrinterException {
        initComponents();
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        printfile.append("\tPenitipan Hewan"
                + "\n      Jln. Buluh Indah No. 7 Karangasem"
                + "\n\tTlp. 0361-234567"
                + "\n"
                + "\nTanggal : " + Tdate.format(timer.getTime())
                // + "\nKasir   : " + "Admin"
                + "\n---------------------------------------------------------------------------"
                + "\nNama Pemilik\t\t" + MenuAdmin.namaPemilik
                + "\nHewan\t\t" + MenuAdmin.namaHewanLainnya
                + "\nJenis\t\t" + MenuAdmin.vjenisHewan
                + "\nMakanan\t\t" + MenuAdmin.vjenisMakanan
                + "\n---------------------------------------------------------------------------"
                + "\nUang Muka\t\t" + "Rp. " + MenuAdmin.uangMuka
                + "\nSisa Bayar\t\t" + "Rp. " + MenuAdmin.sisabayar
                + "\nBayar\t\t" + "Rp. " + MenuAdmin.dibayarkan
                + "\nKembalian\t\t" + "Rp. " + MenuAdmin.kembalian
                + "\n\nPembayaran Lunas"
                + "\nTerimakasih");
        printfile.print();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        printfile = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        printfile.setColumns(20);
        printfile.setRows(5);
        jScrollPane1.setViewportView(printfile);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Printfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Printfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Printfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Printfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Printfile().setVisible(false);
                } catch (PrinterException ex) {
                    Logger.getLogger(Printfile.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea printfile;
    // End of variables declaration//GEN-END:variables
}
